### ISSUE TITLE
TypeError: Cannot read property '2'

### ISSUE THREAD

**Issue by jg3** [irsheep/MMM-SnmpIntSpeed#4]
Hi,

SnmpIntSpeed seems to load up, but it always shows the same value:  50 bps down / 0 bps up.

I'm getting the following error when I start up MM and I really don't know how to make heads or tails of it ...

```
[2020-04-05 10:43:14.450] [LOG]    Whoops! There was an uncaught exception...
[2020-04-05 10:43:14.450] [ERROR]  TypeError: Cannot read property '2' of undefined
    at PrepareData (/home/pi/MagicMirror/modules/MMM-SnmpIntSpeed/node_helper.js:118:30)
    at Session.<anonymous> (/home/pi/MagicMirror/modules/MMM-SnmpIntSpeed/node_helper.js:160:54)
    at Session.emit (events.js:200:13)
    at Session.onClose (/home/pi/MagicMirror/modules/MMM-SnmpIntSpeed/node_modules/net-snmp/index.js:902:7)
    at Socket.emit (events.js:200:13)
    at socketCloseNT (dgram.js:709:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-04-05 10:43:14.454] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-04-05 10:43:14.454] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```
(this error will repeat each polling cycle in the log if I leave MM running)

I am able to successfully scrape my interfaces (but GetInterfaces dies with an error when I try to run it from any other directory; maybe a path issue?)

```
pi@raspberry:~/MagicMirror/modules/MMM-SnmpIntSpeed $ node GetInterfaces.js --version 2 --community public --host 10.39.6.254
{ '1': { ifDescr: 'em0', ifName: 'em0', ifAlias: '' },
  '2': { ifDescr: 'em1', ifName: 'em1', ifAlias: '' },
  '3': { ifDescr: 'em2', ifName: 'em2', ifAlias: '' },
  '4': { ifDescr: 'pflog0', ifName: 'pflog0', ifAlias: '' },
  '5': { ifDescr: 'pfsync0', ifName: 'pfsync0', ifAlias: '' },
  '6': { ifDescr: 'enc0', ifName: 'enc0', ifAlias: '' },
  '7': { ifDescr: 'lo0', ifName: 'lo0', ifAlias: '' },
  '8': { ifDescr: 'em1_vlan1', ifName: 'em1_vlan1', ifAlias: '' },
  '9': { ifDescr: 'em1_vlan6', ifName: 'em1_vlan6', ifAlias: '' },
  '10': { ifDescr: 'em1_vlan3', ifName: 'em1_vlan3', ifAlias: '' },
  '11': { ifDescr: 'em1_vlan9', ifName: 'em1_vlan9', ifAlias: '' },
  '12': { ifDescr: 'ovpns1', ifName: 'ovpns1', ifAlias: '' },
  '13': { ifDescr: 'ovpns2', ifName: 'ovpns2', ifAlias: '' } }
```

For reference, here's the module configuration section of MM's config.js:

```
		{
		  disabled: false,
		  module: "MMM-SnmpIntSpeed",
		  position: "bottom_left",
		  config: {
		    gaugeType: 'minimal',
		    interval: 30,
		    community: 'public',
		    version: 2,
		    host: "pfsense",
		    index: 2,
		  }
		},
```

I'd be obliged for any thoughts as to what is causing this.  Thanks!

**Comment by irsheep** [comment]
Hi the new version should fix this.
